src/Entity/Enquiry.php
<?php

namespace App\Entity;

use App\Generator\EnquiryProposalKeyGenerator;
use App\Repository\EnquiryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnquiryRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Enquiry
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    private $currentPlace;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_address;

    /**
     * @ORM\Column(type="datetime")
     */
    private $check_in_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $check_out_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $enquiry_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $wishes;

    /**
     * @ORM\Column(type="integer")
     */
    private $numberOfPersons;

    /**
     * @var string
     */
    private $code;

    /**
     * @ORM\OneToOne(targetEntity=Offer::class, inversedBy="enquiry", cascade={"persist", "remove"})
     */
    private $offer;

    /**
     * @ORM\ManyToOne(targetEntity=Property::class, inversedBy="enquiries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property;

    /**
     * @ORM\OneToMany(targetEntity=History::class, mappedBy="enquiry")
     */
    private $histories;

    /**
     * @ORM\Column(type="integer")
     */
    private $reservationNumber;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="enquiries")
     * @ORM\JoinColumn(nullable=true)
     */
    private $company;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $client_comment;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $hotel_comment;

    /**
     * @ORM\OneToMany(targetEntity=FollowUp::class, mappedBy="enquiry", cascade="persist")
     */
    private $followUps;

    /**
     * @ORM\OneToMany(targetEntity=EnquiryUpdates::class, mappedBy="enquiry", cascade="persist")
     */
    private $enquiryUpdates;


    /**
     * @ORM\ManyToOne(targetEntity=Age::class, inversedBy="enquiry")
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="enquiries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=RateType::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $ratetype;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class)
     */
    private $country;

    /**
     * @ORM\ManyToOne(targetEntity=Language::class)
     */
    private $language;

    /**
     * @ORM\ManyToOne(targetEntity=TemplateCondition::class)
     */
    private $templateCondition;

    /**
     * @ORM\ManyToOne(targetEntity=TemplateProposal::class)
     */
    private $templateProposal;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $customConditions;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $proposalKey;

    /**
     * @ORM\ManyToOne(targetEntity=CancelReason::class)
     */
    private $cancelReason;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity=RateDisplay::class)
     */
    private $rateDisplay;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $providerId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ageCode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $emptyBedsCharged;

    /**
     * @ORM\OneToMany(targetEntity=BreakdownEnquiry::class, mappedBy="enquiry", orphanRemoval=true)
     */
    private $breakdownEnquiries;

    public function __construct()
    {
        $this->wishes = new ArrayCollection();
        $this->histories = new ArrayCollection();
        $this->followUps = new ArrayCollection();
        $this->check_in_date = new \DateTime();
        $this->active = true;
        $this->enquiryUpdates = new ArrayCollection();
        $this->breakdownEnquiries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCurrentPlace()
    {
        return $this->currentPlace;
    }

    public function setCurrentPlace($currentPlace, $context = [])
    {
        $this->currentPlace = $currentPlace;
    }

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    public function getContactFirstName(): ?string
    {
        return $this->contact_first_name;
    }

    public function setContactFirstName(?string $contact_first_name): self
    {
        $this->contact_first_name = $contact_first_name;

        return $this;
    }

    public function getContactLastName(): ?string
    {
        return $this->contact_last_name;
    }

    public function setContactLastName(?string $contact_last_name): self
    {
        $this->contact_last_name = $contact_last_name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmailAddress(): ?string
    {
        return $this->email_address;
    }

    public function setEmailAddress(string $email_address): self
    {
        $this->email_address = $email_address;

        return $this;
    }

    public function getCheckInDate(): ?\DateTimeInterface
    {
        return $this->check_in_date;
    }

    public function setCheckInDate(\DateTimeInterface $check_in_date): self
    {
        $this->check_in_date = $check_in_date;

        return $this;
    }

    public function getCheckOutDate(): ?\DateTimeInterface
    {
        return $this->check_out_date;
    }

    public function setCheckOutDate(\DateTimeInterface $check_out_date): self
    {
        $this->check_out_date = $check_out_date;

        return $this;
    }

    public function getEnquiryDate(): ?\DateTimeInterface
    {
        return $this->enquiry_date;
    }

    public function setEnquiryDate(\DateTimeInterface $enquiry_date): self
    {
        $this->enquiry_date = $enquiry_date;

        return $this;
    }

    public function getWishes(): ?string
    {
        return $this->wishes;
    }

    public function setWishes(?string $wishes): self
    {
        $this->wishes = $wishes;

        return $this;
    }

    public function getNumberOfPersons(): ?int
    {
        return $this->numberOfPersons;
    }

    public function setNumberOfPersons(int $numberOfPersons): self
    {
        $this->numberOfPersons = $numberOfPersons;

        return $this;
    }

    public function getOffer(): ?Offer
    {
        return $this->offer;
    }

    public function setOffer(?Offer $offer): self
    {
        $this->offer = $offer;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    /**
     * @return string
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * @param string $code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue(): void
    {
        $this->enquiry_date = new \DateTime();
        $this->proposalKey = (new EnquiryProposalKeyGenerator())->create();
    }

    /**
     * @return Collection|History[]
     */
    public function getHistories(): Collection
    {
        return $this->histories;
    }

    public function addHistory(History $history): self
    {
        if (!$this->histories->contains($history)) {
            $this->histories[] = $history;
            $history->setEnquiry($this);
        }

        return $this;
    }

    public function removeHistory(History $history): self
    {
        if ($this->histories->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getEnquiry() === $this) {
                $history->setEnquiry(null);
            }
        }

        return $this;
    }

    public function getReservationNumber(): ?int
    {
        return $this->reservationNumber;
    }

    public function setReservationNumber(int $reservationNumber): self
    {
        $this->reservationNumber = $reservationNumber;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getClientComment(): ?string
    {
        return $this->client_comment;
    }

    public function setClientComment(?string $client_comment): self
    {
        $this->client_comment = $client_comment;

        return $this;
    }

    public function getHotelComment(): ?string
    {
        return $this->hotel_comment;
    }

src/Entity/FollowUp.php
<?php

namespace App\Entity;

use App\Repository\FollowUpRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FollowUpRepository::class)
 */
class FollowUp
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $provide_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity=Enquiry::class, inversedBy="followUps")
     */
    private $enquiry;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $executedDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="followUps")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProvideDate(): ?\DateTimeInterface
    {
        return $this->provide_date;
    }

    public function setProvideDate(\DateTimeInterface $provide_date): self
    {
        $this->provide_date = $provide_date;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getEnquiry(): ?Enquiry
    {
        return $this->enquiry;
    }

    public function setEnquiry(?Enquiry $enquiry): self
    {
        $this->enquiry = $enquiry;

        return $this;
    }

    public function getExecutedDate(): ?\DateTimeInterface
    {
        return $this->executedDate;
    }

    public function setExecutedDate(?\DateTimeInterface $executedDate): self
    {
        $this->executedDate = $executedDate;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/FollowUpController.php
<?php

namespace App\Controller;

use App\Entity\Enquiry;
use App\Entity\FollowUp;
use App\Form\FollowUpType;
use App\Repository\FollowUpRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/follow/up")
 */
class FollowUpController extends AbstractController
{
    /**
     * @var Security
     */
    private $security;

    public function __construct(
        Security $security
    ) {
        $this->security = $security;
    }

    /**
     * @Route("/", name="follow_up_index", methods={"GET"})
     */
    public function index(FollowUpRepository $followUpRepository)
    {
        $propertyId = $this->container->get('session')->get('property_id');
        if (!$propertyId) {
            $this->addFlash('warning', 'No property selected');

            return $this->redirectToRoute('dashboard');
        }

        return $this->render('follow_up/index.html.twig', [
            'followups' => $followUpRepository->findPassed($propertyId),
        ]);
    }

    /**
     * @Route("/new/{id}", name="follow_up_new", methods={"GET","POST"})
     */
    public function new(Request $request, Enquiry $enquiry): Response
    {
        $followUp = new FollowUp();
        $form = $this->createForm(FollowUpType::class, $followUp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $followUp->setEnquiry($enquiry);
            if ($enquiry->getFollowUps()->isEmpty()) {
                $followUp->setNumber(1);
            } else {
                $enquiryId = $enquiry->getId();
                $oldNumber = $this->getDoctrine()->getRepository('App:FollowUp')
                    ->findNumberLastCreated($enquiryId);
                $followUp->setNumber($oldNumber + 1);
            }
            $entityManager->persist($followUp);
            $entityManager->flush();
            $this->container->get('session')->set('active-tab-enquiry', 'enquiry_follow_up');

            return $this->redirectToRoute('enquiry_show', ['id' => $enquiry->getId()]);
        }

        return $this->render('follow_up/new.html.twig', [
            'follow_up' => $followUp,
            'enquiry' => $enquiry,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/validate/{id}", name="follow_up_validate", methods={"GET", "POST"})
     */
    public function validate(FollowUp $followUp): Response
    {
        $followUp->setExecutedDate(new \DateTime());
        $followUp->setUser($this->security->getUser());
        $this->getDoctrine()->getManager()->flush();
        $this->container->get('session')->set('active-tab-enquiry', 'enquiry_follow_up');
        return $this->redirectToRoute('enquiry_show', ['id' => $followUp->getEnquiry()->getId()]);
    }

    /**
     * @Route("/validate/list/{id}", name="follow_up_validate_list", methods={"GET", "POST"})
     */
    public function validateList(FollowUp $followUp): Response
    {
        $followUp->setUser($this->security->getUser());
        $followUp->setExecutedDate(new \DateTime());
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('follow_up_index');
    }

    /**
     * @Route("/show/enquiry/{id}", name="show_follow_up_in_enquiry", methods={"GET", "POST"})
     */
    public function showInEnquiry(FollowUp $followUp): Response
    {
        $this->container->get('session')->set('active-tab-enquiry', 'enquiry_follow_up');
        return $this->redirectToRoute('enquiry_show', ['id' => $followUp->getEnquiry()->getId()]);
    }

    /**
     * @Route("/{id}/edit", name="follow_up_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, FollowUp $followUp): Response
    {
        $form = $this->createForm(FollowUpType::class, $followUp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->container->get('session')->set('active-tab-enquiry', 'enquiry_follow_up');

            return $this->redirectToRoute('enquiry_show', ['id' => $followUp->getEnquiry()->getId()]);
        }

        return $this->render('follow_up/edit.html.twig', [
            'follow_up' => $followUp,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="follow_up_delete", methods={"DELETE"})
     */
    public function delete(Request $request, FollowUp $followUp): Response
    {
        $enquiryId = $followUp->getEnquiry()->getId();

        if ($this->isCsrfTokenValid('delete' . $followUp->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($followUp);
            $entityManager->flush();
            $this->container->get('session')->set('active-tab-enquiry', 'enquiry_follow_up');
        }

        return $this->redirectToRoute('enquiry_show', ['id' => $enquiryId]);
    }
}

templates/follow_up/_delete_form.html.twig
<form method="post" action="{{ path('follow_up_delete', {'id': follow_up.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ follow_up.id) }}">
    <button class="btn"><i class="material-icons">delete</i></button>
</form>

templates/follow_up/_form.html.twig
{{ form_start(form) }}

    {% if enquiry is defined %}
        {{ form_widget(form, {'action': path('enquiry_show', {'id': enquiry.id}), 'method': 'POST'}) }}
    {% else %}
        {{ form_widget(form, {'action': path('enquiry_show', {'id': follow_up.enquiry.id}), 'method': 'POST'}) }}
    {% endif %}
    <button class="btn" id="followup-btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/follow_up/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FollowUp{% endblock %}

{% block body %}
    <h1>Edit FollowUp</h1>

    {{ include('follow_up/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('#followup-btn').click(function(){
            var date_followup = new Date($('#follow_up_provide_date').val());
            var today = new Date();
            if (date_followup < today) {
                if(!confirm('You selected a follow up date in the past, do you want to go ahead?')){
                    return false;
                }
            }
        })
    </script>
{% endblock %}

templates/follow_up/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Follow up index{% endblock %}

{% block body %}
    <h1>List of pending Follow up</h1>

    <table class="striped centered">
        <thead>
        <tr>
            <th>Follow up date</th>
            <th>Chase number</th>
            <th>Reservation number</th>
            <th>Account Manager</th>
            <th>Group name</th>
            <th>Total Room Amount</th>
            <th>Comment</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for followup in followups %}
            {% set nights = 0 %}
            {% set nights = 0 %}
            {% set total_persons = 0 %}
            {% set total_price = 0 %}
            {% if followup.enquiry.offer is not null%}
                {% for room in followup.enquiry.offer.rooms  %}
                    {% set difference = date(room.checkOutDate).diff(date(room.checkInDate)) %}
                    {% set nights = difference.days %}
                    {% set room_price = 0 %}
                    {% set room_price = room.averageRate * room.roomQuantity * nights %}
                    {% set total_price = total_price + room_price %}
                {% endfor %}
            {% endif %}
            <tr>
                <td>{{ followup.provideDate ? followup.provideDate|date('Y-m-d') : '' }}</td>
                <td>{{ followup.number }}</td>
                <td>{{ followup.enquiry.reservationNumber }}</td>
                <td>
                    {% if followup.enquiry.company is not null %}
                        {% if followup.enquiry.company.user is not null %}
                    {{ followup.enquiry.company.user.firstname }} {{ followup.enquiry.company.user.lastname }}
                        {% endif %}
                    {% endif %}
                </td>
                <td>{{ followup.enquiry.groupName }}</td>
                <td>{{ total_price }}</td>
                <td style="width: 30%; text-align: left">{{ followup.comment }}</td>
                <td style="width: 200px">
                    <a href="{{ path('follow_up_validate_list', {'id' : followup.id }) }}" onclick="return confirm('Enquiry chased for sure?');"><button class="btn">Done</button></a>
                    <a href="{{ path('follow_up_edit', {'id' : followup.id }) }}"><button class="btn">Edit</button></a>
                    <a href="{{ path('show_follow_up_in_enquiry', {'id': followup.id}) }}"><button style="margin-top: 5px" class="btn">Show enquiry</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no follow up pending</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/follow_up/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Follow Up{% endblock %}

{% block body %}
    <h1>Create new Follow Up</h1>

    {{ include('follow_up/_form.html.twig') }}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('#followup-btn').click(function(){
            var date_followup = new Date($('#follow_up_provide_date').val());
            var today = new Date();
            if (date_followup < today) {
                if(!confirm('You selected a follow up date in the past, do you want to go ahead?')){
                    return false;
                }
            }
        })
    </script>
{% endblock %}

templates/follow_up/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FollowUp{% endblock %}

{% block body %}
    <h1>Follow Up</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ follow_up.id }}</td>
            </tr>
            <tr>
                <th>Provide_date</th>
                <td>{{ follow_up.provideDate ? follow_up.provideDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ follow_up.comment }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('follow_up_index') }}">back to list</a>

    <a href="{{ path('follow_up_edit', {'id': follow_up.id}) }}">edit</a>

    {{ include('follow_up/_delete_form.html.twig') }}
{% endblock %}